### ISSUE TITLE
Extrae las constantes

### ISSUE THREAD

**Issue by javatlacati** [LaynezCoder/ElectronicStoreToolFX#5]
Para hacer más mantenible el código es mejor si las constantes las pones en la parte superior del código, así cualquier cambio será mucho más rápido.

https://github.com/LaynezCoder/ElectronicStoreToolFX/blob/6f41d73bc77b9d7f5c0a3c428479d4fdef48c0a8/src/com/laynezcoder/controllers/AboutController.java#L57

**Comment by LaynezCoder** [comment]
Te lo agradezco demasiado, procederé a hacer el cambo. Solamente a modo de duda ¿Es necesario declarar la constante con la palabra **static**  o solamente basta con declararlo como **private final tipo NOMBRE_IDENTIFICADOR = valor;**?
